[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://allo-kapri-catalog.onrender.com"
  VITE_WHATSAPP_NUMBER = "244936777484"
  NODE_VERSION = "20"
